persistence true
persistence_location /var/lib/mosquitto/

listener 1883
protocol mqtt

listener 9001
protocol websockets

allow_duplicate_messages false

allow_anonymous false
#password_file /etc/mosquitto/passwords.txt

auth_plugin /mosquitto/go-auth.so

#auth_opt_backends http
#auth_opt_backends files
#auth_opt_check_prefix false
#
#auth_opt_disable_superuser true
#
#auth_opt_http_host http-wait
#auth_opt_http_port 8080
#auth_opt_http_register user, acl, superuser
#auth_opt_http_getuser_uri /https/webhook.example.net/mqttauth/getuser
#auth_opt_http_aclcheck_uri /https/webhook.example.net/mqttauth/aclcheck
#auth_opt_http_superuser_uri /https/webhook.example.net/mqttauth/superuser
#auth_opt_http_with_tls false
#auth_opt_http_verify_peer false
#auth_opt_http_timeout 300
#
#auth_opt_files_password_path /etc/mosquitto/passwords.txt

#auth_opt_log_level debug
auth_opt_backends ldap
auth_opt_cache true
auth_opt_auth_cache_seconds 240
auth_opt_acl_cache_seconds 180

auth_opt_ldap_url ldap://lldap.lldap.svc.cluster.local:3890
auth_opt_ldap_user_dn ou=people,dc=example,dc=com
auth_opt_ldap_group_dn ou=groups,dc=example,dc=com
auth_opt_ldap_bind_dn uid=mosquitto,ou=people,dc=example,dc=com
auth_opt_ldap_bind_password ${MOSQUITTO_LDAP_BIND_PASSWORD}
auth_opt_ldap_user_filter (&(uid=%s)(objectClass=person)(memberOf=mqtt))
auth_opt_ldap_superuser_filter (&(uid=%s)(objectClass=person)(memberOf=mqtt_superuser))
auth_opt_ldap_acl_topic_pattern_attribute mqtt_topic_pattern
auth_opt_ldap_acl_acc_attribute mqtt_topic_acc
