#!/usr/bin/env bash
# Regenerate the Flux bootstrap manifests under kube-cluster/flux-system/ from the
# pinned parameters below, instead of hand-editing those generated files. Use this
# to bump the Flux version or add/remove a controller, then review the diff + commit.
#
#   ./scripts/gen-flux.sh && git diff kube-cluster/flux-system
#
# The output is deterministic: with the values below it reproduces the committed
# gotk-components.yaml / gotk-sync.yaml byte-for-byte (verified). Requires the `flux`
# CLI on PATH — any version works, `--version` pins which manifest set is fetched.
set -euo pipefail
cd "$(dirname "$0")/.."

# ── pinned parameters ────────────────────────────────────────────────────────
FLUX_VERSION="v2.9.1"   # bump to upgrade Flux itself, then re-run + commit the diff
# Default controller set. Add optional ones via COMPONENTS_EXTRA, e.g.
# "image-reflector-controller,image-automation-controller,source-watcher".
COMPONENTS="source-controller,kustomize-controller,helm-controller,notification-controller"
COMPONENTS_EXTRA=""

NAMESPACE="flux-system"
GIT_URL="https://github.com/example/k0s-flux.git"
GIT_BRANCH="main"
GIT_PATH="./kube-cluster/flux-system"
GIT_SECRET="flux-system"   # secret the GitRepository authenticates with (deploy key / token)
SOURCE_INTERVAL="1h"       # how often to poll git (a webhook Receiver makes pushes instant)
SYNC_INTERVAL="10m"

OUT="kube-cluster/flux-system"
# ─────────────────────────────────────────────────────────────────────────────

echo "flux ${FLUX_VERSION} -> ${OUT}/gotk-components.yaml"
flux install --export \
  --version="${FLUX_VERSION}" \
  --namespace="${NAMESPACE}" \
  --components="${COMPONENTS}" \
  ${COMPONENTS_EXTRA:+--components-extra="${COMPONENTS_EXTRA}"} \
  > "${OUT}/gotk-components.yaml"

echo "         -> ${OUT}/gotk-sync.yaml"
{
  echo "# This manifest was generated by flux. DO NOT EDIT."
  flux create source git "${NAMESPACE}" \
    --url="${GIT_URL}" --branch="${GIT_BRANCH}" \
    --interval="${SOURCE_INTERVAL}" --secret-ref="${GIT_SECRET}" --export
  flux create kustomization "${NAMESPACE}" \
    --source="GitRepository/${NAMESPACE}" --path="${GIT_PATH}" \
    --prune=true --interval="${SYNC_INTERVAL}" --export
} > "${OUT}/gotk-sync.yaml"

echo "done. review 'git diff ${OUT}' and commit."
